In [1]:
%run $main.ipynb
datas = main(0)
print(datas)

      gender  seniorCitizen partner dependents  tenure phoneService  \
0     Female              0     Yes         No       1           No
1       Male              0      No         No      34          Yes
2       Male              0      No         No       2          Yes
3       Male              0      No         No      45           No
4     Female              0      No         No       2          Yes
...      ...            ...     ...        ...     ...          ...
7038    Male              0     Yes        Yes      24          Yes
7039  Female              0     Yes        Yes      72          Yes
7040  Female              0     Yes        Yes      11           No
7041    Male              1     Yes         No       4          Yes
7042    Male              0      No         No      66          Yes

         multipleLines internetService onlineSecurity onlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     deviceProtection techSupport streamingTV streamingMovies        contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     paperlessBilling              paymentMethod  monthlyCharges totalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [2]:
datas.describe(include='all')

,gender,seniorCitizen,partner,dependents,tenure,phoneService,multipleLines,internetService,onlineSecurity,onlineBackup,deviceProtection,techSupport,streamingTV,streamingMovies,contract,paperlessBilling,paymentMethod,monthlyCharges,totalCharges,churn
count,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,2,NaN,2,2,NaN,2,3,3,3,3,3,3,3,3,3,2,4,NaN,6531,2
top,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [3]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   seniorCitizen     7043 non-null   int64
 2   partner           7043 non-null   object
 3   dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   phoneService      7043 non-null   object
 6   multipleLines     7043 non-null   object
 7   internetService   7043 non-null   object
 8   onlineSecurity    7043 non-null   object
 9   onlineBackup      7043 non-null   object
 10  deviceProtection  7043 non-null   object
 11  techSupport       7043 non-null   object
 12  streamingTV       7043 non-null   object
 13  streamingMovies   7043 non-null   object
 14  contract          7043 non-null   object
 15  paperlessBilling  7043 non-null   object
 16  paymentMethod     7043 non-null   object
 17  monthlyCharges    7043 non-null   float64
 18  totalCharges      7043 non-null   object
 19  churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
datas.dtypes

gender               object
seniorCitizen         int64
partner              object
dependents           object
tenure                int64
phoneService         object
multipleLines        object
internetService      object
onlineSecurity       object
onlineBackup         object
deviceProtection     object
techSupport          object
streamingTV          object
streamingMovies      object
contract             object
paperlessBilling     object
paymentMethod        object
monthlyCharges      float64
totalCharges         object
churn                object
dtype: object